### ISSUE TITLE
Updating solid-js and babel-preset-solid to 0.24.0 break my buttons

### ISSUE THREAD

**Issue by aminya** [ryansolid/solid#335]
**Describe the bug**
After upgrading the places I used `onClick` are broken.

The examples:
https://github.com/steelbrain/linter-ui-default/blob/2b2f2ca1ed449d4ec8e0f076020aec2831388ce8/lib/tooltip/message.tsx#L101
```js
      <div className={`linter-excerpt ${message.severity}`}>
        {
          // fold butotn if has message description
          message.description && (
            <a href="#" onClick={async () => await toggleDescription()}>
              <span className={`icon linter-icon icon-${state.descriptionShow ? 'chevron-down' : 'chevron-right'}`} />
            </a>
          )
        }
	<div>
```

**To Reproduce**

**Expected behavior**
Click should work

**Reproduction**
This is reproducible inside Atom. I cannot seem to be able to make a separate reproduction outside Atom.
https://github.com/steelbrain/linter-ui-default/

Downgrading Solid completely fixed the issue!

**Additional context**

**Comment by shamsartem** [comment]
I have the same issue. Wanted to try solid for the first time using typescript starter and wasn't able to create even a simple counter because onClick doesn't seem to work

**Comment by ryansolid** [comment]
Yeah I think I see an issue.. but the fact the "click" event is affected for you both is strange. There are plenty of working demos with click on the latest version. 

I did break non-delegated events, but "click" is delegated. This tipped me off: https://github.com/ryansolid/solid/issues/334#issuecomment-773903915

Oh.. compiler version mismatch.. that must be it.. I probably have to update the scripts project. I will update when both are updated.

**Comment by ryansolid** [comment]
Ok...

@shamsartem  I've updated Solid Scripts.. if you clear your node_modules update the dep in your project. You should be good. You should probably update Solid to 0.24.1 as well.

@aminya probably not your fix though. I did fix non-delegated events. Double check your version of babel-plugin-jsx-dom-expressions. I did change the generated output of delegated events. The latest babel-preset-solid should be up to date, but just in case something is up in the lock file/modules. If you look at the compiled output you know you have newer version if you see click handler looking like `$$click`. I changed to dollar signs from underscores, which could be the mismatch if they don't match.

**Comment by aminya** [comment]
I tried to update solid to 0.24.1, but now my build tool fails:

```ps1
× Build failed.
@parcel/transformer-babel: C:UsersaminyDocumentsGitHubJavaScript@linterlinter-ui-defaultlibtooltipindex.tsx: text.replace is not a function
TypeError: C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\lib\tooltip\index.tsx: text.replace is not a function
    at trimWhitespace (C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\node_modules\.pnpm\babel-plugin-jsx-dom-expressions@0.25.2\node_modules\babel-plugin-jsx-dom-expressions\index.js:329:15)
    at transformNode (C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\node_modules\.pnpm\babel-plugin-jsx-dom-expressions@0.25.2\node_modules\babel-plugin-jsx-dom-expressions\index.js:1869:18)
    at C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\node_modules\.pnpm\babel-plugin-jsx-dom-expressions@0.25.2\node_modules\babel-plugin-jsx-dom-expressions\index.js:892:11
    at Array.map (<anonymous>)
    at transformChildren (C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\node_modules\.pnpm\babel-plugin-jsx-dom-expressions@0.25.2\node_modules\babel-plugin-jsx-dom-expressions\index.js:890:8)
    at transformElement (C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\node_modules\.pnpm\babel-plugin-jsx-dom-expressions@0.25.2\node_modules\babel-plugin-jsx-dom-expressions\index.js:482:5)
    at transformNode (C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\node_modules\.pnpm\babel-plugin-jsx-dom-expressions@0.25.2\node_modules\babel-plugin-jsx-dom-expressions\index.js:1863:12)
    at PluginPass.transformJSX (C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\node_modules\.pnpm\babel-plugin-jsx-dom-expressions@0.25.2\node_modules\babel-plugin-jsx-dom-expressions\index.js:1824:18)
    at Object.newFn (C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\node_modules\.pnpm\@babel\traverse@7.12.12\node_modules\@babel\traverse\lib\visitors.js:175:21)
    at NodePath._call (C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\node_modules\.pnpm\@babel\traverse@7.12.12\node_modules\@babel\traverse\lib\path\context.js:55:20)
```

**Comment by ryansolid** [comment]
Ok this is a new feature bug. I have an idea what it is. I added smarter resolution of statics i must be assuming strings in locations they are not. I will get this fixed up.

**Comment by ryansolid** [comment]
Ok that issue should be fixed now too. Update both to 0.24.2.

**Comment by shamsartem** [comment]
@ryansolid thanks for a quick reply. I updated solid-js to 0.24.2, solid-scripts to 0.0.51 and still simple counter doesn't work for me. The same code works for me on the playground though

**Comment by ryansolid** [comment]
@shamsartem I'm fairly certain this is a package issue. I think what I did in Solid Scripts was insufficient for people with it already installed. Can you confirm your installed version of babel-preset-solid matches your version of Solid?

**Comment by aminya** [comment]
Sorry, but the issues are worse now. In addition to the buttons, a lot of things are not rendered for me.

**Comment by ryansolid** [comment]
@shamsartem I tried grabbing an existing starter I had and removed my node_modules, `package-lock.json`, and reinstalled and had no problems. 

@aminya I'm trying to think of what would cause issues. There were some changes I made in 0.23.5 that had bigger effects but the changes for 0.24 were mostly changes to resourceAPI, and which events get delegatred (less now), state getters. The changelog has a pretty good record of things. Since 0.24.0 the biggest change besides bug fixes was smarter evaluation for hoisting static values (ie.. it can detect constants and write them right into the template), I added a new ability to support event binding through components.. it does means event handlers that pass a simple var in need the heavier runtime check. But unclear how any of this would affect rendering.

**Comment by shamsartem** [comment]
@ryansolid thank you very much. sorry for bothering, I think it was package-lock.json that I forgot to remove

**Comment by ryansolid** [comment]
@aminya #348 unveiled a pretty widespread bug with the 0.24.0 release.  I've fixed it in 0.24.7. But it is the sort of thing I could see causing really strange behavior. I'm just trying to guess what could be causing your issue.

**Comment by aminya** [comment]
Updated to 0.24.7, but the issue is still there. The behavior is similar to 0.24.2 (no rendering).

https://github.com/steelbrain/linter-ui-default/pull/629

**Comment by aminya** [comment]
OK. I think the button issue is fixed by updating my dependency that had been build using the old solid. My build system was being configured to use the ES6 built of solid-simple-table which I think imports whatever version solid has. Bumping solid in solid-simple-table, and using it in my linter-ui-default package, fixes the button issue.

However, there is still some rendering issue for my tooltips.

**Comment by aminya** [comment]
Updating to "0.24.12" in [solid-simple-table](https://github.com/aminya/solid-simple-table/pull/6/) now my tests break with this error:
```js
 FAIL  test/SimpleTable.test.tsx
  ● Test suite failed to run

    TypeError: _$template is not a function

      47 |   // Row sorting logic:
      48 |   function sortRows() {
    > 49 |     const currentSortDirection = getSortDirection()
         |                ^
      50 |     // if should reset sort
      51 |     if (
      52 |       currentSortDirection[0] === null &&

      at Object.<anonymous> (src/SimpleTable.tsx:49:16)
      at Object.<anonymous> (demo/simple/index.tsx:2:1)
      at Object.<anonymous> (test/SimpleTable.test.tsx:3:1)
```

**Comment by ryansolid** [comment]
I'm pretty sure it's related to: https://github.com/ryansolid/solid/issues/355

Legacy resolution for SSR requires using the browser field for client builds and reserving the server build. Apparently bundlers have no issue with this but Jest isn't configured to handle it out of the box and requires a custom resolver. My local test and examples were fine. It probably should have been a minor version bump. I tested cross demos and bundlers but missed 3rd party libraries with Jest. 

Any luck with the other issues? I still haven't had any luck reproducing elsewhere. Everyone else with similar issues just needed to update their node modules. I was kind of hoping to resolve this before bumping another minor version if whatever the issue was required more attention.

**Comment by ryansolid** [comment]
Ok I've released presets to work with Jest:

https://github.com/ryansolid/solid-jest

You can see them in use in solid-rx, solid-meta, solid-styled-components in this repo.

**Comment by aminya** [comment]
Thanks! Now, the tests run. The issue in [this comment](https://github.com/ryansolid/solid/issues/335#issuecomment-791876106) is fixed now.

However, I had used a private method to test my clicks `__click` which doesn't work anymore 😁 Is the method renamed?
```ts
    header.__click(new MouseEvent("click"))
```
https://github.com/aminya/solid-simple-table/blob/0285bb092e18b631890945d997a9923b693565b0/test/SimpleTable.test.tsx#L107

**Comment by aminya** [comment]
This the latest error I get on this PR: 
https://github.com/steelbrain/linter-ui-default/pull/629

```js
> cross-env NODE_ENV=production parcel build --target main ./lib/index.ts && npm run babel.globalThis

× Build failed.
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'template'
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'render'
C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\lib\tooltip\index.tsx:43:5
  42 |     })
> 43 |     render(() => <div className="linter-messages">{children}</div>, this.element)
>    |     ^^^^^^
  44 |
  45 |     // move box above the current editing line
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'template'
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'delegateEvents'
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'insert'
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'memo'
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'effect'
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'template'
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'delegateEvents'
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'addEventListener'
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'render'
C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\lib\panel\dock.tsx:58:5
  57 |     this.doPanelResize()
> 58 |     render(() => <PanelComponent delegate={delegate} />, this.element)
>    |     ^^^^^^
  59 |   }
  60 |   // NOTE: Chose a name that won't conflict with Dock APIs
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'template'
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'setAttribute'
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'insert'
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'template'
C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\node_modules\.pnpm\solid-simple-table@0.2.1\node_modules\solid-simple-table\dist\SimpleTable.module.js:1:86
> 1 | rt { template as o, delegateEvents as r, setAttribute as i, memo as c, addEventListener as l, style as s, effect as u, insert as d, cre
>   |      ^^^^^^^^^^^^^
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'delegateEvents'
C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\node_modules\.pnpm\solid-simple-table@0.2.1\node_modules\solid-simple-table\dist\SimpleTable.module.js:1:101
> 1 | s o, delegateEvents as r, setAttribute as i, memo as c, addEventListener as l, style as s, effect as u, insert as d, createComponent as
>   |      ^^^^^^^^^^^^^^^^^^^
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'setAttribute'
C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\node_modules\.pnpm\solid-simple-table@0.2.1\node_modules\solid-simple-table\dist\SimpleTable.module.js:1:122
> 1 | s r, setAttribute as i, memo as c, addEventListener as l, style as s, effect as u, insert as d, createComponent as a } from "solid-js/w
>   |      ^^^^^^^^^^^^^^^^^
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'addEventListener'
C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\node_modules\.pnpm\solid-simple-table@0.2.1\node_modules\solid-simple-table\dist\SimpleTable.module.js:1:152
> 1 | s c, addEventListener as l, style as s, effect as u, insert as d, createComponent as a } from "solid-js/web";export default {};const v
>   |      ^^^^^^^^^^^^^^^^^^^^^
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'style'
C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\node_modules\.pnpm\solid-simple-table@0.2.1\node_modules\solid-simple-table\dist\SimpleTable.module.js:1:175
> 1 | s l, style as s, effect as u, insert as d, createComponent as a } from "solid-js/web";export default {};const v = o("<table><thead><tr>
>   |      ^^^^^^^^^^
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'effect'
C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\node_modules\.pnpm\solid-simple-table@0.2.1\node_modules\solid-simple-table\dist\SimpleTable.module.js:1:187
> 1 | s s, effect as u, insert as d, createComponent as a } from "solid-js/web";export default {};const v = o("<table><thead><tr></tr></thead
>   |      ^^^^^^^^^^^
@parcel/core: node_modules\.pnpm\solid-js@0.24.13\node_modules\solid-js\web\dist\server.js does not export 'insert'
C:\Users\aminy\Documents\GitHub\JavaScript\@linter\linter-ui-default\node_modules\.pnpm\solid-simple-table@0.2.1\node_modules\solid-simple-table\dist\SimpleTable.module.js:1:200
> 1 | s u, insert as d, createComponent as a } from "solid-js/web";export default {};const v = o("<table><thead><tr></tr></thead><tbody></tbo
>   |      ^^^^^^^^^^^

```

**Comment by ryansolid** [comment]
Yeah I switched it to $$ under the recommendation that on custom elements using `__` was dangerous as it's a common pattern for internal variables. We discussed maps and lookups and symbols but I decided to just change it. I didn't realize it was being used so didn't make much of it. This was the issue: https://github.com/ryansolid/solid/issues/319

**Comment by ryansolid** [comment]
I see.. you are getting the node version not the browser version. I did a lot of changing of how exports work to support a number of  different systems with ultimately an isomorphic import. So write the same code other than the entry and compiles for client and server.

So let's figure out why you are getting the node version. First does the environment support [conditional exports](https://nodejs.org/api/packages.html#packages_conditional_exports). Bundlers like webpack and rollup have support for them. If so I'd imagine this would just work. If dealing with legacy environment does it support the `browser` field. That was only consistent way to ship client and browser versions I could find. It meant for jest I needed to do a remap, and I imagine it might be similar here. There's more details than this when consuming 3rd party libraries although if you aren't doing SSR probably don't need to worry about it.

This is electron right.. is there a field I can export for it? A way to set `browser` mainfield?

**Comment by aminya** [comment]
> This is electron right.. is there a field I can export for it? A way to set browser mainfield?

Yes, it is Electron, but I bundle the code using a recent version of Parcel nightly. The code is here if you want to try it yourself.
https://github.com/steelbrain/linter-ui-default/tree/solid-update

I use Parcel [aliases](https://v2.parceljs.org/features/module-resolution/#aliases) for my `solid-simple-table` dependency.
```
  "alias": {
    "solid-simple-table": "solid-simple-table/dist/SimpleTable.module"
  },
```

Not a Solid issue, but removing the alias picks up the TypeScript code for some reason, so it doesn't work at all
```
× Build failed.
@parcel/transformer-js: Unexpected token, expected "," (16:33)
SyntaxError: Unexpected token, expected "," (16:33)
    at Parser._raise (C:\linter-ui-default\node_modules\.pnpm\@babel\parser@7.12.15\node_modules\@babel\parser\lib\index.js:776:17)
    at Parser.raiseWithData (C:\linter-ui-default\node_modules\.pnpm\@babel\parser@7.12.15\node_modules\@babel\parser\lib\index.js:769:17)
    at Parser.raise (C:\linter-ui-default\node_modules\.pnpm\@babel\parser@7.12.15\node_modules\@babel\parser\lib\index.js:737:17)
    at Parser.unexpected (C:\linter-ui-default\node_modules\.pnpm\@babel\parser@7.12.15\node_modules\@babel\parser\lib\index.js:9183:16)
    at Parser.expect (C:\linter-ui-default\node_modules\.pnpm\@babel\parser@7.12.15\node_modules\@babel\parser\lib\index.js:9169:28)
    at Parser.parseBindingList (C:\linter-ui-default\node_modules\.pnpm\@babel\parser@7.12.15\node_modules\@babel\parser\lib\index.js:9588:14)
    at Parser.parseFunctionParams (C:\linter-ui-default\node_modules\.pnpm\@babel\parser@7.12.15\node_modules\@babel\parser\lib\index.js:12511:24)
    at Parser.parseFunction (C:\linter-ui-default\node_modules\.pnpm\@babel\parser@7.12.15\node_modules\@babel\parser\lib\index.js:12489:10)
    at Parser.parseFunctionStatement (C:\linter-ui-default\node_modules\.pnpm\@babel\parser@7.12.15\node_modules\@babel\parser\lib\index.js:12124:17)
    at Parser.parseStatementContent (C:\linter-ui-default\node_modules\.pnpm\@babel\parser@7.12.15\node_modules\@babel\parser\lib\index.js:11814:21)
C:\linter-ui-default\node_modules\.pnpm\solid-simple-table@0.2.1\node_modules\solid-simple-table\src\SimpleTable.tsx:16:33
  15 |
> 16 | export function SimpleTable(props: Props<IndexType>) {
>    |                                 ^
  17 |   const [getSortDirectionSignal, setSortDirection] = createSignal<SortDirectionSignal>()
  18 |   const [getRows, setRows] = createSignal<RowsSignal>(props.rows)
 ERROR  Command failed with exit code 1.
```

**Comment by ryansolid** [comment]
Parcel respects the `browser` field to my knowledge. It also was the library that introduced the `source`. Its low config makes it difficult to see exactly what is going on. I found some issue around parcel 2 and better electron support but I'm not sure I follow it completely. I can tell from the error what the issue is, but I don't quite get why it's happening or what to do about it. It's clearly importing from the `main` field which is for node environments (SSR) and you want the browser env which I have under `browser` field. But how Parcel makes those decisions I have no way. I use Parcel in code sandbox without issue, but I'm not sure how to debug it since Parcel sort of just works or it doesn't. No config to tweak.

**Comment by aminya** [comment]
It actually allows configuration through aliases, but not sure why I need to do that manually. Now, the build works with the following config:
```json
  "alias": {
    "solid-simple-table": "solid-simple-table/dist/SimpleTable.module",
    "solid-js": "solid-js/dist/solid.js",
    "solid-js/web": "solid-js/web/dist/web.js"
  },
```
Next, step is testing the functionality.

**Comment by aminya** [comment]
Now, tooltips don't show up. Solid-simple-table works without any issues.
https://github.com/steelbrain/linter-ui-default/blob/5511790acc098416c25697aedf843a308da41e3b/lib/tooltip/index.tsx#L43

Is there any way I can debug this?

**Comment by ryansolid** [comment]
I think we need to narrow down to whether its the event not firing or whether its the reactivity not tracking. That changes what should be looked into.

**Comment by ryansolid** [comment]
@aminya  Any progress? I was unclear how I can best help resolve this issue.

**Comment by aminya** [comment]
Well, strangely the issue seems to have been fixed by other means [when I merged master into my solid-update branch](https://github.com/steelbrain/linter-ui-default/pull/629). I didn't update solid or the code changes weren't related to this case, but Rollup for example got updated. So, not sure if Rollup was causing the issue.

**Comment by ryansolid** [comment]
I wouldn't put it past babel. I saw some issues a month or so back about persistent state in traversal.  But that's great to hear.

**Comment by aminya** [comment]
Thanks for all the help! I am closing this issue for now.

**Comment by aminya** [comment]
@ryansolid I hit this error again, but I managed to fix it. The issue was not Babel! See this PR to see the changes I made. 
https://github.com/steelbrain/linter-ui-default/commit/1ab4e54cae6b0b352b7e15ad479faa2c991f456b

It seems that using the following code didn't work after Solid 0.24. 

```js
    const children: Array<Solid.JSX.Element> = []
    messages.forEach(message => {
      if (message.version === 2) {
        children.push(<MessageElement key={message.key} delegate={delegate} message={message} />)
      }
    })
    render(() => <div className="linter-messages">{children}</div>, this.element)
```
I switched to using `For` which fixes the issue and also probably gives better performance.

```js
function TooltipElement(messages: Message[], delegate: Delegate) {
  return (
    <div className="linter-messages">
      <For each={messages}>
        {message => {
          if (message.version === 2) {
            return <MessageElement key={message.key} delegate={delegate} message={message} />
          }
          return undefined
        }}
      </For>
    </div>
  )
}
```

**Comment by ryansolid** [comment]
I'm surprised this ever worked after 0.20.0 since you were creating elements outside of a reactive root. Nesting is better. In this case where messages never update you might be fine with just using `.map` but it's probably just good practice to use `<For>`
